"""Structural invariants of the reachable permutation set.

A permutation machine is characterised cryptanalytically by which subset of the
symmetric group its encryption permutations can occupy.  This experiment
measures, for Enigma, Purple and Violet, the three observables that expose the
three classical invariants: the fixed-point count, the signature, and the
existence of an invariant partition of the alphabet.  It also certifies, by
Schreier--Sims, the group generated by Violet's reachable set.
"""

from __future__ import annotations

import json
import os
import sys
from collections import Counter
from math import comb, factorial, log2

import numpy as np
import matplotlib.pyplot as plt

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "violet_core"))
sys.path.insert(0, os.path.dirname(__file__))

from violet import (N, Enigma, Mode, Purple, VioletMachine, cycle_type, fixed_points,  # noqa: E402
                    sign, STRATEGIC)
import vizstyle as vs  # noqa: E402

OUT = os.path.join(os.path.dirname(__file__), "..", "figures")
DATA = os.path.join(os.path.dirname(__file__), "..", "analysis", "results")
SAMPLES = 20000


def block_crossing_rate(streams: np.ndarray) -> float:
    """Largest fraction of the alphabet that any single block can retain.

    For every candidate block size we search greedily for the best invariant
    block under the observed permutations; a machine with a genuine invariant
    partition returns 1.0 for the true block, a machine without one returns the
    trivial value.
    """
    n = streams.shape[1]
    reach = np.zeros((n, n), dtype=bool)
    for perm in streams:
        reach[np.arange(n), perm] = True
    # Transitive closure of the reachability digraph: an invariant block is a
    # union of strongly connected components with no outgoing edge.
    closure = reach.copy()
    for k in range(n):
        closure |= np.outer(closure[:, k], closure[k, :])
    closed_sizes = [int(closure[i].sum()) for i in range(n)]
    return min(closed_sizes) / n


def main() -> None:
    vs.use_paper_style()
    os.makedirs(OUT, exist_ok=True)
    os.makedirs(DATA, exist_ok=True)
    rng = np.random.default_rng(20260725)

    # --- reachable permutation samples -----------------------------------
    violet = VioletMachine.canonical(STRATEGIC, mode=Mode.CLOSED, key_seed=11)
    msg = rng.integers(0, N, size=SAMPLES)
    V = violet.permutation_stream(SAMPLES, xs=msg)

    enigma = Enigma(("I", "II", "III"), (0, 0, 0), (0, 0, 0),
                    [(0, 5), (1, 9), (2, 14), (3, 20), (4, 25)])
    E = enigma.permutation_stream(SAMPLES)

    purple = Purple(seed=7)
    P = purple.permutation_stream(SAMPLES)

    R = np.stack([rng.permutation(N) for _ in range(SAMPLES)])

    families = {"Violet": V, "Enigma": E, "Purple": P, "Uniform $S_{26}$": R}

    stats = {}
    for name, S in families.items():
        fp = np.array([fixed_points(S[t]) for t in range(len(S))])
        sg = np.array([sign(S[t]) for t in range(2000)])
        invol = np.mean([np.array_equal(S[t][S[t]], np.arange(N)) for t in range(2000)])
        stats[name] = {
            "mean_fixed_points": float(fp.mean()),
            "var_fixed_points": float(fp.var()),
            "p_zero_fixed_points": float((fp == 0).mean()),
            "frac_even": float((sg == 1).mean()),
            "frac_involution": float(invol),
            "min_invariant_block_fraction": block_crossing_rate(S[:4000]),
            "distinct_cycle_types": len({cycle_type(S[t]) for t in range(4000)}),
        }

    # --- group generated by Violet's reachable set ------------------------
    try:
        from sympy.combinatorics import Permutation, PermutationGroup
        gens = [Permutation(list(map(int, V[t]))) for t in range(0, 400, 7)]
        G = PermutationGroup(gens)
        order = G.order()
        stats["Violet"]["generated_group_order_log2"] = float(log2(order))
        stats["Violet"]["generated_is_full_symmetric"] = bool(order == factorial(N))
    except Exception as exc:  # pragma: no cover - optional dependency path
        stats["Violet"]["generated_group_error"] = str(exc)

    # --- structural class sizes, in bits ----------------------------------
    fpf_involutions = 1
    for i in range(1, N, 2):
        fpf_involutions *= i                      # 25!! fixed-point-free involutions
    classes = {
        "Enigma\n(reflector class)": log2(fpf_involutions),
        "Purple\n(6/20 stabiliser)": log2(factorial(6) * factorial(20)),
        "Rotor bank\n(signature coset)": log2(factorial(N) // 2),
        "Violet\n(unconstrained)": log2(factorial(N)),
    }
    stats["structural_class_bits"] = classes
    stats["fpf_involution_count"] = fpf_involutions
    stats["blocks_6_20_count"] = comb(N, 6)

    with open(os.path.join(DATA, "invariants.json"), "w") as fh:
        json.dump(stats, fh, indent=2)

    # ---------------------------------------------------------------- figure
    fig, axes = plt.subplots(1, 4, figsize=(13.0, 3.1))

    # (a) fixed points
    ax = axes[0]
    order_names = ["Violet", "Enigma", "Purple", "Uniform $S_{26}$"]
    colours = [vs.BLUE, vs.ORANGE, vs.AQUA, vs.INK_3]
    bins = np.arange(-0.5, 7.5, 1)
    for name, colour in zip(order_names, colours):
        S = families[name]
        fp = np.array([fixed_points(S[t]) for t in range(len(S))])
        h, _ = np.histogram(fp, bins=bins, density=True)
        ax.plot(np.arange(0, 7), h, marker="o", color=colour, label=name,
                lw=1.8 if name != "Uniform $S_{26}$" else 1.2,
                ls="-" if name != "Uniform $S_{26}$" else "--")
    ax.set_xlabel("letters encrypting to themselves")
    ax.set_ylabel("probability")
    ax.set_ylim(0, 1.05)
    vs.title(ax, "a  Self-encryption", "Enigma is pinned at zero")
    ax.legend(loc="upper right")
    vs.despine(ax)

    # (b) signature
    ax = axes[1]
    fracs = [stats[n]["frac_even"] for n in order_names]
    bars = ax.bar(range(4), fracs, color=colours, width=0.62)
    ax.axhline(0.5, color=vs.INK_3, lw=0.9, ls="--")
    ax.text(3.45, 0.52, "unconstrained", fontsize=7.5, color=vs.INK_3, ha="right")
    ax.set_xticks(range(4))
    ax.set_xticklabels(["Violet", "Enigma", "Purple", "Uniform"], fontsize=7.5)
    ax.set_ylabel("fraction of even permutations")
    ax.set_ylim(0, 1.05)
    vs.title(ax, "b  Signature", "a frozen signature leaks one bit")
    vs.label_bar(ax, bars, fmt="{:.2f}", dy=0.02)
    vs.despine(ax)

    # (c) invariant partition
    ax = axes[2]
    fracs = [stats[n]["min_invariant_block_fraction"] for n in order_names]
    bars = ax.bar(range(4), fracs, color=colours, width=0.62)
    ax.set_xticks(range(4))
    ax.set_xticklabels(["Violet", "Enigma", "Purple", "Uniform"], fontsize=7.5)
    ax.set_ylabel("smallest invariant block / 26")
    ax.set_ylim(0, 1.09)
    vs.title(ax, "c  Invariant partition", "Purple never leaves its 6-set")
    vs.label_bar(ax, bars, fmt="{:.2f}", dy=0.02)
    vs.despine(ax)

    # (d) structural class size
    ax = axes[3]
    names = list(classes)
    vals = [classes[k] for k in names]
    cols = [vs.ORANGE, vs.AQUA, vs.YELLOW, vs.BLUE]
    bars = ax.barh(range(len(names)), vals, color=cols, height=0.58)
    ax.set_yticks(range(len(names)))
    ax.set_yticklabels(names, fontsize=7.2)
    ax.invert_yaxis()
    ax.set_xlabel("$\\log_2$ |reachable class|")
    ax.set_xlim(0, 100)
    for rect, v in zip(bars, vals):
        ax.text(v + 1.4, rect.get_y() + rect.get_height() / 2, f"{v:.1f}",
                va="center", fontsize=7.5, color=vs.INK_2)
    vs.title(ax, "d  Room to move", "how much of $S_{26}$ is reachable")
    vs.despine(ax, left=True)
    ax.grid(axis="y", visible=False)

    fig.tight_layout()
    fig.savefig(os.path.join(OUT, "fig_invariants.pdf"))
    fig.savefig(os.path.join(OUT, "fig_invariants.png"))
    print(json.dumps(stats, indent=2)[:2400])


if __name__ == "__main__":
    main()
